# URL de conexión: dice a Spring Boot dónde está la base de datos
# localhost = "en este mismo computador", 5432 = el puerto, travelmate_db = el nombre de la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/travelmate_db

# Usuario administrador de PostgreSQL
spring.datasource.username=postgres

# La contraseña que definiste al instalar PostgreSQL
spring.datasource.password=travelmate

# Dialecto SQL que debe usar Hibernate (el motor que traduce Java <-> SQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Muestra en consola cada consulta SQL que se ejecuta (útil mientras aprendes)
spring.jpa.show-sql=true

# "validate" = Spring revisa que tus clases Java coincidan con las tablas, pero no las toca
spring.jpa.hibernate.ddl-auto=validate